### PR TITLE
Updated to Play Billing 6.0.0

### LINKED ISSUE #61: Update Android Play Billing Library
message in google play:

Android 14 has introduced new [security changes](https://notifications.google.com/g/p/ANiao5o2037_oMi178DOp_mL3eGTrzo_pP4uR7uaPzsmF9mhy73YA9rTUSULMW-o10aOkYe-wnt-Lymc6XayEf0DExrt-7mRfGOMvkMKvQ130Q5cPoZpmH7WlNm-lZ09JYBtQ7BW1c-snRxrQzb4D6Q7pZfUVjI2sCoOHRzRUf0tM9GbUSAB0GijRn98yPJUQa7F2kGeG3JO2u8i0uKONoQfp7wfsIFjFoMk21KavVvlwKoodQ_Y9fLHQ8RuAzUtHubozyfhVk5QJey635m2aYh-YIKGpsentmdWKCZG-Qw) which affect apps targeting Android 14. In order to ensure compatibility, Google has released [Play Billing Library version 6.0.1 and 5.2.1](https://notifications.google.com/g/p/ANiao5qs8DgOzTLz8Jrn4F69TdcBnkzRKx79mpToKmGv-Yoi_s6-pwFdPMefQgXTMitwEw2QSp3jAsk_48cMuhnO-H63cYAvUn4cJ6uFaoL2IRv8EmLdK2y3MUQgi170trSXyPV-paeHRtsZN9inQhAciYBkNOkWZLJpR5y5bvxHufseXjBpYuaM-hy9HgDiV0k-R2yR0nK4_s8aHGcLuuiiB9FP32R0nho0VD1_QX9SbCBDZXoZVj5OlYwdYRsVMwLfa1mYpl_lIKI3DOsHJ4l8bg). When updating your app to target Android 14, following these [migration steps](https://notifications.google.com/g/p/ANiao5rKr3ZOZ-uwXLJEIc1VuS6vkDdrJ5gOZGY0ryCd7gBdXZ-CQ3aTqzh_SVgebZx38kDaCI0m57RrY1YvEmtEJlrNKHEhBIuMdbSuewQJ_x4U0mJ-f6sxi8lkSLsl06jn5uhAAnFiYZEqXaqkerpyrP5etyWd1k2Ge-86_jhPL51qktt_mhsVd4GSKYSi4zGXgptgc3koHWZ9n5Dwr-s6yFvWUcsREbsyNks5LWF469sdxsgnYX_f59KRyHIqxkTQjuAu4Q), you will need to update your app to either of these versions of the Play Billing Library to be compatible with the recent security changes.

These changes only affect your app when it starts targeting Android 14. Users running Android 14 while your app is not targeting Android 14 are unaffected.

image

### PR DESCRIPTION
**Pull request by britzl**
Fixes #61

### CODE REVIEW

**Review by AGulev — APPROVED** [review]

**Comment by baochungit** [comment]
Hi, I know it's not my business but I'm here to aware that the app will be crashed when using billing 6.0.0 along with https://github.com/defold/extension-firebase/archive/refs/tags/2.0.2.zip

**Comment by AGulev** [comment]
@baochungit thatnk you for testing.
Could you please provide crash log?

**Comment by baochungit** [comment]
@AGulev sorry I don't have a real Android 14 device to debug and get crash log. I was using BrowserStack.
I think there's no issue with this billing version. There must be something incompatible with current version of extension firebase.

**Comment by britzl** [comment]
I will test this before merging.

**Comment by baochungit** [comment]
@britzl sr that made you confused, just re-tested and see it's crashed without the firebase extension. I'll create a ticket for you guys to check sometimes then

**Pull request merged**
